### ISSUE TITLE
Backup errors

### ISSUE THREAD

**Issue by kaimano** [DrDBanner/inmanage#2]
Hello, and first thank for your script. It's amazing!

However, I cannot perform the backup in a shared hosting. this is the error:
`mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces`

I tried creating a .my.cnf file with the DB credentials, which worked on a local LAMP system, but without success.

**Comment by DrDBanner** [comment]
I am a bit unsure what's the question. It's literally stated there: Your Database User has no PROCESS rights which is mandatory. End of story.

Try to convince your share hosting provider to give you that particular right on your DB.

**Comment by DrDBanner** [comment]
We can circumvent this by cutting out the `tablespaces` information when we invoke the dump. This MAY have implications on the functionality of the dump. So, I'll add a switch to the configuration in the near future. 

- [ ] Create Switch for `--no-tablespaces` on mysqldumps

**Comment by kaimano** [comment]
Ok, thanks

**Comment by DrDBanner** [comment]
I created something. Can you try with the development branch?

```
cd .inmanage
git pull
git checkout develop
cd ..
./inmanage.sh
```

Should add the new configuration to the configuration file. Next time you do a backup it should do the mysqldump with the --no-tablespaces switch. Please report it it works.

**Comment by DrDBanner** [comment]
@kaimano PING!
