### ISSUE TITLE
Update deletes snappdf binarys

### ISSUE THREAD

**Issue by LarsK1** [DrDBanner/inmanage#3]
Hi,
thanks for your awesome script. I only noticed a minor bug. Every time an update takes place the chrome binary for snappdf is missing. When I download it again, it works just fine.

**Comment by DrDBanner** [comment]
Hi, thanks for reporting. Isn't it like the binaries for chrome are supposed to be installed in ANY location BUT the invoiceninja installation folder. So, at least that's what I'd do intuitively. If not, I'll dig deeper on that matter.

**Comment by LarsK1** [comment]
Hi,
@DrDBanner yes - they need to be installed using vendor/beganovich/snappdf download.

They are't part of the downloaded file.

**Comment by DrDBanner** [comment]
For unknown reason my multipass stopped working. Can you show me how the folder `vendor/beganovich/snappdf/versions/` is populated at your end? Then I'd just copy the latest version over if snappdf is enabled.

**Comment by LarsK1** [comment]
@DrDBanner 
![image](https://github.com/user-attachments/assets/e994c404-bf9e-4135-a1e2-e284b042280d)

**Comment by LarsK1** [comment]
I think it would make more sense to just download it using  `vendor/beganovich/snappdf download`. Siince that also updates chrome to the newest version. Otherwise users would be stuck with older versons

**Comment by DrDBanner** [comment]
Hey Lars, you may checkout the develop branch and start an update?

**Comment by DrDBanner** [comment]
@LarsK1 ping

**Comment by LarsK1** [comment]
Hey @DrDBanner ,
sorry for the late reply. Works perfect. Thanks for the quick fix!
