### ISSUE TITLE
Switching to user ''.

### ISSUE THREAD

**Issue by dieterth** [DrDBanner/inmanage#7]
Hi DrBanner,
i am testing the new Version, and it seems i found a new bug.
If i get the actual Version of inmanage, try to create a new install of invoiceninja the script stops with the message:
/srv/ninja5$ ./inmanage.sh clean_install 
All required commands are available.
Environment check starts.
Self configuration found
Switching to user ''.
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-D directory] [-g group] [-h host] [-p prompt] [-R directory] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-D directory] [-g group] [-h host] [-p prompt] [-R directory] [-T timeout] [-u user] file ...

In the inimage Subdirectory i made the .env.provision and the .env.example holds the same data. Its the data from my old (invoiceninja 4.5.50 versin with all the credentials for the database and so on)
The target ist to migrate the data to the actual Invoice Ninja V5.
I have dumpd the mariadb data completely in a sql file and restore it to the new Database for Invoice ninja V5.
The nginx Webserver is stoppd under this process.
My Hope is to start Invoice Ninja V5 with this data to enshure getting my historical data back in the actual environment.
But ...

Best regards, Dieter

**Comment by dieterth** [comment]
I tested it twice, completely reinstalled Debian 11.
Then reinstalled the script, saved my target platform as .env.inmanage according to the .env from IN 4.5.50 and called the script with /var/www/ninja5$ ./inmanage.sh clean_install.
The result is:
All required commands are available.
Environment check starts.
Self configuration found
Switching to user ''. (the variable is empty!)
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-D directory] [-g group] [-h host] [-p prompt] [-R directory] [-T timeout] [-u user] [VAR=value] [-i|-s]
 [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-D directory] [-g group] [-h host] [-p prompt] [-R directory] [-T timeout] [-u user] file ...

Best regards, Dieter

**Comment by DrDBanner** [comment]
seems another "Debian" thing. It's handling the sudo command different. Will need to fix that if I can detect which version is in play. Will take some time but I'll fix it as well.

**Comment by dieterth** [comment]
Good Morning DrBanner,
thank you for your help!
sudo -V give me = Sudo-Version 1.9.5p2
/etc/debian_version is = 11.11
Best regards, Dieter

**Comment by DrDBanner** [comment]
I just tried on debian. Worked without problems. Was a clean environment started from scratch. 

<img width="887" alt="Bildschirmfoto 2024-12-22 um 12 26 16" src="https://github.com/user-attachments/assets/f9cf57bd-202d-4d70-94cc-aeebc88fbaeb" />

**Comment by DrDBanner** [comment]
Even if I don't enforce the user it works. If I run with my local user it aborts as expected due to failed file creation. So, can't reproduce what's on your end going on. 

```
vboxuser@vbox:/var/www/html/ninja-base$ uname -a
Linux vbox 6.1.0-27-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.115-1 (2024-11-01) x86_64 GNU/Linux
```

<img width="887" alt="Bildschirmfoto 2024-12-22 um 12 33 14" src="https://github.com/user-attachments/assets/a7d4e50d-51de-419b-914f-5978c53610fa" />

**Comment by DrDBanner** [comment]
maybe check your .env.inmanage file if the variable for the user doesn't contain the default value of www-data ...

**Comment by DrDBanner** [comment]
no reply. not reproducible.
